import { describe, it, expect, vi, beforeEach } from 'vitest'

const { readFileSync } = vi.hoisted(() => ({ readFileSync: vi.fn() }))

vi.mock('node:fs', () => ({
  default: { readFileSync },
  readFileSync,
}))

import { parseChangelog } from '@/lib/changelog'

const STABLE_HEADER = '# [2.2.0](https://github.com/o/r/compare/v2.1.0...v2.2.0) (2026-10-01)'
const PATCH_HEADER = '## [2.2.1](https://github.com/o/r/compare/v2.2.0...v2.2.1) (2026-10-05)'

describe('parseChangelog', () => {
  it('parses a stable release with Features/Bug Fixes sections into New/Fixed entries', () => {
    const raw = `${STABLE_HEADER}

### Features

* **popup:** add drag and drop reordering ([abc1234](https://github.com/o/r/commit/abc1234))

### Bug Fixes

* fix a rendering glitch ([def5678](https://github.com/o/r/commit/def5678))
`
    const entries = parseChangelog(raw)
    expect(entries).toHaveLength(1)
    expect(entries[0].version).toBe('v2.2.0')
    expect(entries[0].date).toBe('October 1, 2026')
    expect(entries[0].changes).toEqual([
      { type: 'New', text: 'popup: add drag and drop reordering' },
      { type: 'Fixed', text: 'fix a rendering glitch' },
    ])
  })

  it('accepts a level-2 (patch) release heading the same as a level-1 heading', () => {
    const raw = `${PATCH_HEADER}

### Bug Fixes

* patch a bug ([abc1234](https://github.com/o/r/commit/abc1234))
`
    const entries = parseChangelog(raw)
    expect(entries).toHaveLength(1)
    expect(entries[0].version).toBe('v2.2.1')
  })

  it('maps Performance Improvements, Reverts, and Code Refactoring onto Improved', () => {
    const raw = `${STABLE_HEADER}

### Performance Improvements

* speed up group render ([a](https://github.com/o/r/commit/a1234567))

### Reverts

* revert a bad change ([b](https://github.com/o/r/commit/b1234567))

### Code Refactoring

* simplify the store ([c](https://github.com/o/r/commit/c1234567))
`
    const entries = parseChangelog(raw)
    expect(entries[0].changes.every((c) => c.type === 'Improved')).toBe(true)
    expect(entries[0].changes).toHaveLength(3)
  })

  it('filters out prerelease versions (-beta.N / -alpha.N / -rc.N)', () => {
    const raw = `${STABLE_HEADER}

### Features

* stable feature ([abc1234](https://github.com/o/r/commit/abc1234))

# [2.2.0-beta.2](https://github.com/o/r/compare/v2.2.0-beta.1...v2.2.0-beta.2) (2026-09-28)

### Features

* beta-only feature ([def5678](https://github.com/o/r/commit/def5678))

# [2.2.0-alpha.1](https://github.com/o/r/compare/v2.1.0...v2.2.0-alpha.1) (2026-09-20)

### Features

* alpha-only feature ([aaa0000](https://github.com/o/r/commit/aaa0000))

# [2.2.0-rc.1](https://github.com/o/r/compare/v2.1.0...v2.2.0-rc.1) (2026-09-22)

### Features

* rc-only feature ([bbb1111](https://github.com/o/r/commit/bbb1111))
`
    const entries = parseChangelog(raw)
    expect(entries).toHaveLength(1)
    expect(entries[0].version).toBe('v2.2.0')
  })

  it('drops a release heading with no recognized-section changes under it', () => {
    // e.g. a release that only contained docs:/chore:/test: commits — commit-analyzer
    // wouldn't have bumped a version for those alone, but guard the parser anyway.
    const raw = `${STABLE_HEADER}

### Documentation

* update the README ([abc1234](https://github.com/o/r/commit/abc1234))
`
    expect(parseChangelog(raw)).toEqual([])
  })

  it('returns an empty array for an empty string', () => {
    expect(parseChangelog('')).toEqual([])
  })

  // Real output verified: this fixture was generated by building the site against a
  // throwaway repo-root CHANGELOG.md written in this exact shape (multi-commit Features
  // section, a scoped and an unscoped commit, a scoped Bug Fixes commit, and a Performance
  // Improvements section), confirming both the section/scope parsing AND that the file gets
  // traced into the deployed route's bundle (see next.config.ts's outputFileTracingRoot/
  // outputFileTracingIncludes comment). The throwaway file was deleted afterwards — kept only
  // as this string so semantic-release's real CHANGELOG.md is never shadowed by a hand-written
  // one committed to the tree.
  it('parses a realistic multi-section, multi-commit release exactly like semantic-release would generate', () => {
    const raw = `# [2.2.0](https://github.com/example-org/tabmerger/compare/v2.1.0...v2.2.0) (2026-10-01)


### Features

* **popup:** add drag and drop reordering ([abc1234](https://github.com/example-org/tabmerger/commit/abc1234abc1234abc1234abc1234abc1234abcd))
* add AI-powered session naming ([def5678](https://github.com/example-org/tabmerger/commit/def5678def5678def5678def5678def5678defa))


### Bug Fixes

* **sync:** resolve last-write-wins conflict on rapid edits ([1112223](https://github.com/example-org/tabmerger/commit/1112223111222311122231112223111222311a2))


### Performance Improvements

* memoize group render to cut popup jank ([3334445](https://github.com/example-org/tabmerger/commit/3334445333444533344453334445333444533b3))
`
    const entries = parseChangelog(raw)
    expect(entries).toHaveLength(1)
    expect(entries[0].version).toBe('v2.2.0')
    expect(entries[0].date).toBe('October 1, 2026')
    expect(entries[0].changes).toEqual([
      { type: 'New', text: 'popup: add drag and drop reordering' },
      { type: 'New', text: 'add AI-powered session naming' },
      { type: 'Fixed', text: 'sync: resolve last-write-wins conflict on rapid edits' },
      { type: 'Improved', text: 'memoize group render to cut popup jank' },
    ])
  })
})

describe('getGeneratedChangelog', () => {
  // getGeneratedChangelog() memoizes at module scope (see lib/changelog.ts) so a warm
  // serverless instance only reads + parses CHANGELOG.md once. That means each test here
  // needs a genuinely fresh module instance — vi.resetModules() + a fresh dynamic import —
  // otherwise the first test's result would leak into every test after it via the cache.
  beforeEach(() => {
    readFileSync.mockReset()
    vi.resetModules()
  })

  it('returns an empty array, not an error, when CHANGELOG.md does not exist yet', async () => {
    const err = Object.assign(new Error('ENOENT'), { code: 'ENOENT' })
    readFileSync.mockImplementation(() => {
      throw err
    })
    const fresh = await import('@/lib/changelog')
    expect(fresh.getGeneratedChangelog()).toEqual([])
  })

  it('re-throws non-ENOENT read errors instead of silently swallowing them', async () => {
    const err = Object.assign(new Error('EACCES'), { code: 'EACCES' })
    readFileSync.mockImplementation(() => {
      throw err
    })
    const fresh = await import('@/lib/changelog')
    expect(() => fresh.getGeneratedChangelog()).toThrow('EACCES')
  })

  it('parses the file contents when CHANGELOG.md exists', async () => {
    readFileSync.mockReturnValue(`${STABLE_HEADER}

### Features

* a feature ([abc1234](https://github.com/o/r/commit/abc1234))
`)
    const fresh = await import('@/lib/changelog')
    const entries = fresh.getGeneratedChangelog()
    expect(entries).toHaveLength(1)
    expect(entries[0].version).toBe('v2.2.0')
  })

  it('memoizes: only reads the file once across repeated calls within the same module instance', async () => {
    readFileSync.mockReturnValue(`${STABLE_HEADER}

### Features

* a feature ([abc1234](https://github.com/o/r/commit/abc1234))
`)
    const fresh = await import('@/lib/changelog')
    fresh.getGeneratedChangelog()
    fresh.getGeneratedChangelog()
    fresh.getGeneratedChangelog()
    expect(readFileSync).toHaveBeenCalledTimes(1)
  })

  it('caches the empty (ENOENT) result too, rather than re-reading a missing file every call', async () => {
    const err = Object.assign(new Error('ENOENT'), { code: 'ENOENT' })
    readFileSync.mockImplementation(() => {
      throw err
    })
    const fresh = await import('@/lib/changelog')
    expect(fresh.getGeneratedChangelog()).toEqual([])
    expect(fresh.getGeneratedChangelog()).toEqual([])
    expect(readFileSync).toHaveBeenCalledTimes(1)
  })
})
