// Extra beta-guide popup screenshots (added after beta-screenshots.ts so that
// script's images are never regenerated by accident): Now Open, the drag
// variants (tab sort, window sort, window -> group, drop zones, Now Open tab
// -> group, multi-group), and the tab reminder editor. Unsigned, demo build,
// light theme, 1600x1200 webp — same look as the rest of packages/web/public/beta.
// Each beat is isolated: a failure logs and the popup is reloaded so one bad
// beat never blocks the others.
import type { Page } from "@playwright/test";
import { launchDemoContext } from "./lib/launchDemoContext";
import { BETA_OUT_DIR, dragTo, saveWebp, settle } from "./lib/betaShot";
import fs from "node:fs";

const only = process.argv.slice(2);

async function main() {
    fs.mkdirSync(BETA_OUT_DIR, { recursive: true });
    const { context, page } = await launchDemoContext(undefined, 2, "light");

    async function beat(name: string, fn: () => Promise<void>) {
        if (only.length && !only.includes(name)) return;
        try {
            await fn();
        } catch (e) {
            console.warn(`[beta-extra] FAILED ${name}: ${(e as Error).message.split("\n")[0]}`);
        }
        await page.mouse.move(0, 0).catch(() => null);
        await page.reload().catch(() => null);
        await page.waitForLoadState("domcontentloaded");
        await page.waitForTimeout(900);
    }

    const sidebarRow = (p: Page, name: string) =>
        p.locator("[data-sidebar-group-index]").filter({ has: p.getByText(name, { exact: true }) });

    // 1. Now Open selected.
    await beat("now-open", async () => {
        await page.getByText("Now Open", { exact: true }).first().click();
        await settle(page);
        await saveWebp(page, "now-open.webp");
    });

    // 2. Reorder a tab inside one window card (Work: 5 tabs in one window).
    await beat("drag-sort-tabs", async () => {
        await page.getByText("Work", { exact: true }).first().click();
        await settle(page);
        const handles = page.locator('[aria-label^="Drag to reorder tab"]');
        await dragTo(page, handles.nth(3), handles.nth(1), 8);
        await saveWebp(page, "drag-sort-tabs.webp");
    });

    // Research -> Split windows gives a group with several windows.
    const splitResearch = async () => {
        await page.getByText("Research", { exact: true }).first().click();
        await page.getByText("Research", { exact: true }).first().click({ button: "right" });
        await page.waitForTimeout(300);
        await page.getByText("Split windows", { exact: true }).click();
        await page.waitForTimeout(700);
    };

    // 3. Reorder window cards within a group.
    await beat("drag-sort-windows", async () => {
        await splitResearch();
        await settle(page);
        const grips = page.locator('[aria-label^="Drag to reorder window"]');
        await dragTo(page, grips.nth(0), grips.nth(2), 10);
        await saveWebp(page, "drag-sort-windows.webp");
    });

    // 4. A whole window onto a sidebar group.
    await beat("drag-window-to-group", async () => {
        await page.getByText("Research", { exact: true }).first().click(); // split persists in IndexedDB across the reload
        await settle(page);
        const grips = page.locator('[aria-label^="Drag to reorder window"]');
        if ((await grips.count()) < 2) await splitResearch();
        await dragTo(page, grips.nth(1), sidebarRow(page, "Shopping"), 12, -70);
        await saveWebp(page, "drag-window-to-group.webp");
    });

    // 5. Drop zones: "Drop here for a new window" + "Drop for a new group" while dragging a tab.
    await beat("drag-drop-zones", async () => {
        await page.getByText("Work", { exact: true }).first().click();
        await settle(page);
        const handle = page.locator('[aria-label^="Drag to reorder tab"]').first();
        const zone = page.getByTestId("new-window-dropzone");
        await dragTo(page, handle, zone);
        await saveWebp(page, "drag-drop-zones.webp");
    });

    // 6. A live tab from Now Open onto a saved group.
    await beat("drag-now-open-tab", async () => {
        await page.getByText("Now Open", { exact: true }).first().click();
        await settle(page);
        const handle = page.locator('[aria-label^="Drag to reorder tab"]').first();
        await dragTo(page, handle, sidebarRow(page, "Work"), 12, -70);
        await saveWebp(page, "drag-now-open-tab.webp");
    });

    // 7. Several groups selected in the sidebar, dragged together.
    await beat("multi-group-drag", async () => {
        await page.getByRole("button", { name: "Select items" }).click();
        await page.waitForTimeout(300);
        for (const g of ["Work", "Research", "Shopping"]) await page.getByLabel(`Select ${g}`).click();
        await settle(page);
        const grip = page.locator('[aria-label^="Drag to reorder group: Work"]');
        await dragTo(page, grip, page.locator('[aria-label^="Drag to reorder group: Reading List"]'), 12);
        await saveWebp(page, "multi-group-drag.webp");
    });

    // 8. Tab reminder: editor open, then the set state (clock icon).
    await beat("tab-reminder", async () => {
        await page.getByText("Work", { exact: true }).first().click();
        await settle(page);
        const title = page.getByText("Q3 Planning", { exact: false }).first();
        await title.click({ button: "right" });
        await page.waitForTimeout(400);
        await page.getByRole("menuitem", { name: "Remind me…" }).click();
        await page.waitForTimeout(500);
        await settle(page);
        await saveWebp(page, "tab-reminder.webp");
        await page.getByRole("button", { name: "1 hour" }).click();
        await page.waitForTimeout(600);
        await settle(page);
        await saveWebp(page, "tab-reminder-set.webp");
    });

    await context.close();
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
