name: Danger JS

on: [pull_request]

jobs:
  pr-checks:
    runs-on: windows-2022

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Use NodeJS ${{ matrix.node }} & Cache
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i --only=dev

      - name: Danger Checks
        run: pnpm exec danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
